name 'formatron_reverse_proxy'
version '0.1.3'
description 'Formatron reverse proxy cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/reverse-proxy-cookbook'
issues_url 'https://github.com/formatron/reverse-proxy-cookbook/issues'
supports 'ubuntu'
depends 'formatron_common'
depends 'formatron_nginx'
